# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see:
# https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric properties
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.16.3

# Mod properties
mod_id=mapsyncer
mod_name=MapSyncer
mod_version=mapsyncer-rebuild-26.1.2-0.3
maven_group=com.mapsyncer
mod_authors=RuoChennn, ShanHe_YF
mod_description=Syncs server-side explored areas to client's Xaero World Map

# Dependencies
fabric_api_version=0.151.0+26.1.2

# Xaero's World Map version
xaero_worldmap_version=1.40.11
