modLoader="javafml"
loaderVersion="[47,)"
license="GPL-3.0"

[[mods]]
modId="mapsyncer"
version="${version}"
displayName="MapSyncer"
description="Syncs server-side explored areas to client's Xaero World Map"
authors="Ruo_Chen"

[[dependencies.mapsyncer]]
modId="forge"
mandatory=true
type="required"
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.mapsyncer]]
modId="minecraft"
mandatory=true
type="required"
versionRange="${minecraft_range_forge}"
ordering="NONE"
side="BOTH"